on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if it is 'NOT RELEASED'
        shell: bash
        run: |
          [[ ! -z $(tail -1 CHANGES.txt | grep -o 'NOT RELEASED') ]] && echo 'NOT RELEASED detected! Skip release.' && exit 1 || exit 0
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: release.md
          draft: false
          prerelease: false
